name: CI/CD Pipeline

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1
      env:
        AWS_REGION: ap-south-1  
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 

    - name: Build and Push Docker Image
      run: |
        docker build -t 730335253188.dkr.ecr.ap-south-1.amazonaws.com/py-three-tier:latest .
        docker push 730335253188.dkr.ecr.ap-south-1.amazonaws.com/py-three-tier:latest

    - name: Deploy to ECS
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: my-app-task.json 
        service: my-app-service  # Replace with your actual ECS service name
        cluster: three-tier  # Replace with your actual ECS cluster name
        wait-for-service-stability: true
