name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1
      with:
        region:  # e.g., us-east-1

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: your_aws_account_id.dkr.ecr.your_aws_region.amazonaws.com/your_ecr_repository_name:latest

    - name: Deploy to ECS
      uses: einaregilas/ecs-deploy@v1
      with:
        cluster: your_cluster_name
        service: your_service_name
        task_definition: your_task_definition
        region: your_aws_region
        wait-for-service-stability: true
